# Generated by Django 3.1.6 on 2021-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_auto_20210317_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='profile_page.Class'),
        ),
    ]
