# Generated by Django 3.1.6 on 2021-03-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_profile_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, to='profile_page.Class'),
        ),
    ]
