# Generated by Django 3.1.6 on 2021-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_auto_20210317_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='profile_page.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=200)),
                ('from_user', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('to_user', 'from_user')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_requests',
            field=models.ManyToManyField(blank=True, to='profile_page.FriendRequest'),
        ),
    ]
