# Generated by Django 3.1.6 on 2021-04-12 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0012_auto_20210405_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['days', 'start_time']},
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='profile_page.profile'),
        ),
    ]
