# Generated by Django 3.1.6 on 2021-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0014_auto_20210412_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-days', 'class_name']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location_sharing',
            new_name='schedule_sharing',
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='profile_page.profile'),
        ),
    ]
